refactor list functions

diff --git a/rush b/rush
--- a/rush
+++ b/rush
@@ -44,6 +44,7 @@ rush_usage() {
   echo
   printf "%s\n" "$(bold "Package Commands:")"
   printf "  %s   Install a package. (default)\n" "$(green "get")        "
+  printf "  %s   Install a package using a menu.\n" "$(green "menu")       "
   printf "  %s   Uninstall a package.\n" "$(green "undo")       "
   printf "  %s   Install a package from a remote repo.\n" "$(green "snatch")     "
   printf "  %s   Copy a package between local repositories.\n" "$(green "copy")       "
@@ -463,6 +464,28 @@ rush_get_usage() {
     printf "  rush ruby\n"
     printf "  rush get ruby --force\n"
     printf "  rush get centos:ruby\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+rush_menu_usage() {
+  printf "rush menu - Install a package using a menu.\n\n"
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  rush menu\n"
+  printf "  rush menu --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(green "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -1083,9 +1106,9 @@ list_display_item() {
   local package="$1"
   local infofile="$2"
   local repo="$3"
-  local simple width
+  local simple="$4"
+  local width
 
-  simple=${args[--simple]}
   width=$((${COLUMNS:-80} + 9))
 
   [[ "$repo" != "default" ]] && package="$repo:$package"
@@ -1102,9 +1125,9 @@ list_display_item() {
 # src/lib/list_show_repo.sh
 list_show_repo() {
   local repo_or_package="$1"
-  local search="${args[--search]}"
-  local simple=${args[--simple]}
-  local all=${args[--all]}
+  local search="$2"
+  local simple="$3"
+  local all="$4"
   local repo="$repo_or_package"
   local package glob repo_path infofile regex package_name
 
@@ -1135,7 +1158,7 @@ list_show_repo() {
   if [[ ${glob[0]} =~ .*\*.* ]]; then
     infofile="$repo_path/$package/info"
     if [[ -f "$infofile" ]]; then
-      list_display_item "$package" "$infofile" "$repo"
+      list_display_item "$package" "$infofile" "$repo" "$simple"
     elif [[ ! $simple ]]; then
       red "nothing in $repo repo"
     fi
@@ -1150,7 +1173,7 @@ list_show_repo() {
 
       if [[ $infofile =~ $regex ]]; then
         package_name="${BASH_REMATCH[1]}"
-        list_display_item "$package_name" "$infofile" "$repo"
+        list_display_item "$package_name" "$infofile" "$repo" "$simple"
       fi
     done
   fi
@@ -1340,36 +1363,40 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -W "$(_rush_completions_filter "--default --help --ignore --name --shallow --ssh -d -h -i -n -s -w")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'edit\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'pull\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'push\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--all --chmod --help --message -a -h -m -x")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'show\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'undo\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help --verbose -h -v")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'copy\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --force --help -f -h")" -- "$cur")'
+  echo $'    \'list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--all --help --simple -a -h -s")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'info\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'list\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--all --help --simple -a -h -s")" -- "$cur")'
+  echo $'    \'copy\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --force --help -f -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'undo\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help --verbose -h -v")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'menu\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'show\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'push\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--all --chmod --help --message -a -h -m -x")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'pull\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'edit\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'get\'*)'
@@ -1384,12 +1411,12 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--all --help --simple -a -h -s")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'e\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
   echo $'    \'s\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'e\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'l\'*)'
@@ -1425,7 +1452,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help --version -h -v a add c clone completions config copy default download e edit g get i info l list ls p pull push r remove s search show snatch u undo update upload")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_rush_completions_filter "$(rush list -s -a) --help --version -h -v a add c clone completions config copy default download e edit g get i info l list ls menu p pull push r remove s search show snatch u undo update upload")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -1656,6 +1683,17 @@ rush_get_command() {
 }
 
 # :command.function
+rush_menu_command() {
+
+  # src/commands/menu.sh
+  echo "# This file is located at 'src/commands/menu.sh'."
+  echo "# It contains the implementation for the 'rush menu' command."
+  echo "# The code you write here will be wrapped by a function named 'rush_menu_command()'."
+  echo "# Feel free to edit this file; your changes will persist when regenerating."
+
+}
+
+# :command.function
 rush_undo_command() {
 
   # src/commands/undo.sh
@@ -1817,12 +1855,15 @@ rush_list_command() {
 
   # src/commands/list.sh
   repo_or_package=${args[repo_or_package]}
+  search=${args[--search]}
+  simple=${args[--simple]}
+  all=${args[--all]}
 
   if [[ $repo_or_package ]]; then
-    list_show_repo "$repo_or_package"
+    list_show_repo "$repo_or_package" "$search" "$simple" "$all"
   else
     for k in $(config_keys); do
-      list_show_repo "$k"
+      list_show_repo "$k" "$search" "$simple" "$all"
     done
   fi
 
@@ -1997,6 +2038,13 @@ parse_requirements() {
       action="get"
       shift
       rush_get_parse_requirements "$@"
+      shift $#
+      ;;
+
+    menu)
+      action="menu"
+      shift
+      rush_menu_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2743,6 +2791,65 @@ rush_get_parse_requirements() {
 }
 
 # :command.parse_requirements
+rush_menu_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        rush_menu_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  missing_deps=
+  # :dependency.filter
+  if ! command -v fzf >/dev/null 2>&1; then
+    printf "missing dependency: fzf\n" >&2
+    missing_deps=1
+  fi
+
+  if [[ -n $missing_deps ]]; then
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="menu"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 rush_undo_parse_requirements() {
   local key
 
@@ -3395,6 +3502,7 @@ run() {
     "config") rush_config_command ;;
     "default") rush_default_command ;;
     "get") rush_get_command ;;
+    "menu") rush_menu_command ;;
     "undo") rush_undo_command ;;
     "snatch") rush_snatch_command ;;
     "copy") rush_copy_command ;;
